### ISSUE TITLE
build error in Windows

### ISSUE THREAD

**Issue by navono** [egorodet/MethaneKit#87]
**Describe the bug**
1. with Debug mode, cannot find `Windows SDK`
2. after fix `Windows SDK` issue, it will generate `error C2220` error in third libraries

**Steps To Reproduce**

**Expected behavior**
Compile and run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS
    Win10
 - Version
    19043
 - Build environment
    Visual Studio 2019 Community, 16.10.3
    Windows SDK 19041
    CLion 2021.1.3

**How to fix**
Issue 1: `FindWindowsSDK.cmake` -> `_winsdk_win10vers`, add current Windows SDK version bumber
Issue 2: In project root `CMakeLists.txt` line 121, change `/WX` to `/WX-` or just delete `/WX`

**Comment by egorodet** [comment]
Thanks for reporting and investigating the problem! Seems like you already have a workaround. I will look into fixing it next week.

**Comment by egorodet** [comment]
Hello @navono, I was not able to reproduce the problem on the same version of Windows and SDK. Could you provide more details about how you run the build and attach full build log? Also please try to build with `Build\Windows\Build.bat` and check if it works for you (generated solution should include both Release and Debug configurations).

**Comment by egorodet** [comment]
CMake generation issue related to finding of the new Windows SDK version is now fixed. 

@navono, I did not reproduce any compilation errors in MSVC build configurations with the latest Windows SDK. Please note that Clang build configurations are currently not supported (they are added for experimental purposes). If you still experience any compilation errors or warnings, please open separate issue with detailed description of how you build the code (preferrably with command line examples) and attach full build logs, so that it would be possible to reproduce the issue.
